In [35]:
print("reck98")
!(which python)
!(python --version)

reck98
/run/media/reck98/Others/Development/ML_NLP_DL/nlp/.venv/bin/python
Python 3.12.12

In [36]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import nltk

from pathlib import Path as FilePath
# from rich import print
import string

import warnings
warnings.filterwarnings("ignore")

In [37]:
TEXT_FILE_PATH = FilePath("/run/media/reck98/Others/Development/ML_NLP_DL/nlp/public/train.txt")

print(TEXT_FILE_PATH)

/run/media/reck98/Others/Development/ML_NLP_DL/nlp/public/train.txt

In [38]:
original_df = pd.read_csv(TEXT_FILE_PATH, sep=";", header=None, names=["text", "emotion"])

original_df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [39]:
df = original_df.copy()

In [40]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [41]:
df['emotion'].value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text     16000 non-null  str
 1   emotion  16000 non-null  str
dtypes: str(2)
memory usage: 250.1 KB

In [43]:
unique_emotions = df['emotion'].unique()

print(unique_emotions)

<StringArray>
['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
Length: 6, dtype: str

In [44]:
emotions_numbers = {}

for emo in unique_emotions:
    emotions_numbers[emo] = unique_emotions.tolist().index(emo)
    
emotions_numbers

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [45]:
df['emotion'] = df['emotion'].map(emotions_numbers)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [46]:
df['text'] = df['text'].apply(
    lambda x: x.lower()
)

In [47]:
def remove_punctuation(text):
    return text.translate(str.maketrans("", "", string.punctuation))


df['text'] = df['text'].apply(remove_punctuation)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [48]:
def remove_numbers(text = ""):
    new = ""
    
    for i in text:
        if not i.isdigit():
            new += i
    return new


df['text'] = df['text'].apply(remove_numbers)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [49]:
def remove_emojis(text=""):
    new = ""

    for i in text:
        if i.isascii():
            new += i

    return new

df['text'] = df['text'].apply(remove_emojis)

In [50]:
texts = df['text'].tolist()