In [1]:
print("reck98")
!(which python)
!(python --version)

reck98
/run/media/reck98/Others/Development/ML_NLP_DL/Ml-algorithms/.venv/bin/python
Python 3.12.12

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from pathlib import Path as FilePath
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

warnings.filterwarnings("ignore")

FILE_PATH = FilePath("cleaned_data.csv")

In [5]:
df = pd.read_csv(FILE_PATH)
df.head()

   survived  pclass  sex       age  sibsp  parch      fare  embarked  alone
0         0       2    1 -0.590495      1      0 -0.500240         2      0
1         1       0    0  0.643971      1      0  0.788947         0      0
2         1       2    0 -0.281878      0      0 -0.486650         2      1
3         1       0    0  0.412509      1      0  0.422861         2      0
4         0       2    1  0.412509      0      0 -0.484133         2      1

In [7]:
X_test, X_train, y_test, y_train = train_test_split(
    df.drop("survived", axis=1),
    df["survived"],
    test_size=0.2,
    random_state=42,
)

In [9]:
X_test.head()

     pclass  sex       age  sibsp  parch      fare  embarked  alone
707       0    0 -0.590495      0      0  2.404961         2      1
239       2    0  0.003524      1      0 -0.355197         0      0
381       2    1  0.181046      0      0 -0.486650         2      1
791       2    0  0.003524      6      2  0.754050         2      0
682       2    1 -1.207728      5      2  0.298036         2      0

In [17]:
def modelEvaluation(model, X_test, y_test):
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))
    return y_pred


def modelTraining(X_train, y_train, X_test, y_test, n = 5):
    model = KNeighborsClassifier(n_neighbors=n)
    
    model.fit(X_train, y_train)
    return modelEvaluation(model, X_test, y_test)

In [16]:
for i in [1, 3, 5, 7, 9]:
    modelTraining(X_test=X_test, y_test=y_test, X_train=X_train, y_train=y_train, n=i)
    print("\n")

              precision    recall  f1-score   support

           0       0.75      0.81      0.78       440
           1       0.64      0.56      0.60       271

    accuracy                           0.71       711
   macro avg       0.70      0.69      0.69       711
weighted avg       0.71      0.71      0.71       711



              precision    recall  f1-score   support

           0       0.76      0.84      0.80       440
           1       0.69      0.58      0.63       271

    accuracy                           0.74       711
   macro avg       0.72      0.71      0.71       711
weighted avg       0.73      0.74      0.73       711



              precision    recall  f1-score   support

           0       0.77      0.84      0.81       440
           1       0.70      0.60      0.65       271

    accuracy                           0.75       711
   macro avg       0.74      0.72      0.73       711
weighted avg       0.75      0.75      0.75       711



              precision    recall  f1-score   support

           0       0.78      0.84      0.81       440
           1       0.70      0.61      0.65       271

    accuracy                           0.75       711
   macro avg       0.74      0.72      0.73       711
weighted avg       0.75      0.75      0.75       711



              precision    recall  f1-score   support

           0       0.78      0.86      0.82       440
           1       0.73      0.61      0.66       271

    accuracy                           0.76       711
   macro avg       0.75      0.73      0.74       711
weighted avg       0.76      0.76      0.76       711