In [97]:
print("reck98")
!(which python)
!(python --version)

reck98
/run/media/reck98/Others/Development/ML_NLP_DL/Ml-algorithms/.venv/bin/python
Python 3.12.12

In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path as FilePath
import os
from sklearn.model_selection import train_test_split

print(os.getcwd())

/run/media/reck98/Others/Development/ML_NLP_DL/Ml-algorithms/supervised/linear-regression

In [99]:
FILE_PATH = FilePath("../../EDA/public/csv-files/insurance_final.csv")
try:
    orginal_df = pd.read_csv(FILE_PATH)
    df = orginal_df.copy()
except Exception as e:
    print(e)

In [100]:
df.head()

,is_female,is_smoker,is_southeast,is_overweight,is_obese,is_healthy,age,charges
0,1,1,0,1,0,0,-1.440418,16884.92400
1,0,0,1,0,1,0,-1.511647,1725.55230
2,0,0,1,0,1,0,-0.799350,4449.46200
3,0,0,0,0,0,1,-0.443201,21984.47061
4,0,0,0,1,0,0,-0.514431,3866.85520

In [101]:
X = df.drop(columns=['charges'])
y = df['charges']

In [102]:
X

,is_female,is_smoker,is_southeast,is_overweight,is_obese,is_healthy,age
0,1,1,0,1,0,0,-1.440418
1,0,0,1,0,1,0,-1.511647
2,0,0,1,0,1,0,-0.799350
3,0,0,0,0,0,1,-0.443201
4,0,0,0,1,0,0,-0.514431
...,...,...,...,...,...,...,...
1332,0,0,0,0,1,0,0.767704
1333,1,0,0,0,1,0,-1.511647
1334,1,0,1,0,1,0,-1.511647
1335,1,0,0,1,0,0,-1.297958
1336,1,1,0,1,0,0,1.551231

In [103]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1332    10600.54830
1333     2205.98080
1334     1629.83350
1335     2007.94500
1336    29141.36030
Name: charges, Length: 1337, dtype: float64

In [104]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [105]:
X_train.head()

,is_female,is_smoker,is_southeast,is_overweight,is_obese,is_healthy,age
1036,1,1,0,0,1,0,0.411556
467,1,0,0,0,1,0,1.195083
39,0,1,0,0,1,0,1.480002
30,0,1,0,0,1,0,-1.226729
242,1,0,0,1,0,0,1.123853

In [106]:
y_train.head()

1036    39725.51805
467     12643.37780
39      48173.36100
30      35585.57600
242     35160.13457
Name: charges, dtype: float64

In [107]:
len(X_train.columns)

## total x points will be 8 then --> 7 columns and 1 bias term

7

In [108]:
X = X_train.values
y = y_train.values

print(X.shape, y.shape)

(895, 7) (895,)

In [109]:
m, n = X.shape

w = np.zeros(n)
b = 0

In [110]:
def predict(X, w, b):
    return np.dot(X, w) + b

In [111]:
def compute_cost(X, y, w, b):
    m = len(y)
    y_pred = predict(X, w, b)
    cost = (1/m) * np.sum((y_pred - y) ** 2)
    return cost

In [112]:
from tqdm import tqdm

def gradient_descent(X, y, w, b, lr, iterations):
    m = len(y)

    for i in tqdm(range(iterations)):
        y_pred = predict(X, w, b)

        # gradients
        dw = (2/m) * np.dot(X.T, (y_pred - y))
        db = (2/m) * np.sum(y_pred - y)

        # update
        w = w - lr * dw
        b = b - lr * db

        # # optional logging
        # if i % 10000 == 0:
        #     cost = compute_cost(X, y, w, b)
        #     print(f"Iteration {i}, Cost: {cost}")
        

    return w, b

In [113]:
w, b = gradient_descent(X, y, w, b, lr=0.0001, iterations=10000)

print(b, w)

100%|██████████| 10000/10000 [00:00<00:00, 110386.01it/s]

6952.635150980022 [2005.21650077 7451.01331193 1578.10979029 1598.22555142 4343.69691207
  978.30075355 2890.79847548]

In [114]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [115]:
model.fit(X_train, y_train)
print(model.intercept_, model.coef_)

3662.8480260542565 [   66.44290545 22796.18683832  -251.84512769  2794.2388356
  6748.99213378  2212.10585651  3575.95418098]

In [116]:
y_pred = model.predict(X_test)

In [122]:
from sklearn.metrics import mean_squared_error, r2_score

print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))


def adjusted_r2(r2, n, p):
    return 1 - (1 - r2) * (n - 1) / (n - p - 1)


print(adjusted_r2(r2_score(y_test, y_pred), len(y_test), len(X_test.columns)))

39244432.52906917
0.7692867839860134
0.7655656030825619

In [124]:
import pickle

with open("insurance-model.pkl", "wb") as f:
    pickle.dump(model, f)